using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI_Learn.Data
{
    public class StudentData
    {
        //now these two things are configured in StudentConfig.cs
        //[Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This tells EF that the Id is auto-generated by the DB
        public int ID { get; set; }
        public string StudentName { get; set; }
        //public string Name { get; set; } //if StudentName from StudentDTO has to be mapped with StudentData
        public string Email {  get; set; }
        public string Address { get; set; }
    }
}
